export const styles = {
  root: 'flex animate-pulse flex-col gap-8',
  backBar: 'h-4 w-32 rounded bg-border',
  hero: 'grid gap-6 md:grid-cols-2 md:gap-10',
  thumbnail: 'aspect-square w-full rounded-2xl bg-border',
  info: 'flex flex-col gap-4',
  badge: 'h-5 w-24 rounded bg-border',
  nameLine1: 'h-8 w-3/4 rounded bg-border',
  nameLine2: 'h-8 w-1/2 rounded bg-border',
  price: 'h-7 w-28 rounded bg-border',
  textLine: 'h-4 w-full rounded bg-border',
  textLineShort: 'h-4 w-2/3 rounded bg-border',
  button: 'mt-2 h-12 w-full rounded-xl bg-border sm:w-40',
  section: 'flex flex-col gap-3',
  sectionTitle: 'h-5 w-40 rounded bg-border',
  reviewItem: 'flex flex-col gap-2 rounded-xl border border-border bg-surface p-4',
  reviewHeader: 'flex items-center justify-between',
  reviewAuthor: 'h-4 w-24 rounded bg-border',
  reviewRating: 'h-4 w-20 rounded bg-border',
} as const
